/**
 * ROUGH STUB — Post-submission report page. Shows completion status, download button is disabled
 * until Kavin's AI engine generates the PDF report.
 * Restyle and rebuild as needed. All API calls go through api.js — don't change those.
 * Routes: /report (protected — requires Cognito token)
 */
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getAssessmentStatus } from './api';
import { getToken } from './auth';
import './Report.css';

export default function Report() {
  const navigate = useNavigate();
  const [status, setStatus] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = getToken();
    getAssessmentStatus(token)
      .then(data => setStatus(data))
      .catch(() => navigate('/login'))
      .finally(() => setLoading(false));
  }, [navigate]);

  if (loading) {
    return (
      <div className="report-container">
        <div className="report-loading">Loading...</div>
      </div>
    );
  }

  const submittedDate = status?.submittedAt
    ? new Date(status.submittedAt).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
      })
    : 'Today';

  return (
    <div className="report-container">
      <header className="report-header">
        <button className="report-back" onClick={() => navigate('/dashboard')}>← Dashboard</button>
        <div className="report-logo">AIRES</div>
        <div />
      </header>

      <main className="report-main">
        <div className="report-card">
          <div className="report-icon">📊</div>
          <h1 className="report-title">Assessment Complete</h1>
          <p className="report-sub">
            Thank you for completing the AIRES LITE AI Risk Assessment.
            Your personalized risk report is being generated by our AI engine.
          </p>

          <div className="report-status-box">
            <div className="report-status-item">
              <span className="report-status-label">Questions Answered</span>
              <span className="report-status-value">
                {status?.answeredCount || 0} / {status?.totalQuestions || 0}
              </span>
            </div>
            <div className="report-status-item">
              <span className="report-status-label">Status</span>
              <span className="report-status-value report-status-done">Submitted</span>
            </div>
            <div className="report-status-item">
              <span className="report-status-label">Submitted On</span>
              <span className="report-status-value">{submittedDate}</span>
            </div>
          </div>

          <div className="report-next-steps">
            <h3>What happens next?</h3>
            <ul>
              <li>Our AI engine is analysing your responses</li>
              <li>A comprehensive risk report will be generated within 24 hours</li>
              <li>You will receive the report at your registered email address</li>
              <li>The report includes a remediation plan tailored to your organization</li>
            </ul>
          </div>

          <button className="report-download" disabled>
            Download Report (Generating...)
          </button>

          <p className="report-help">
            Questions? Contact us at{' '}
            <a href="mailto:Info@bizcomgrp.com">Info@bizcomgrp.com</a>
          </p>
        </div>
      </main>
    </div>
  );
}
